-- Seed data for game_questions table
-- 30 Riddles, 30 Jokes, 30 Trivia questions

-- RIDDLES (30)
INSERT INTO game_questions (category, question, answer) VALUES
('riddle', 'What has to be broken before you can use it?', 'An egg'),
('riddle', 'I''m tall when I''m young, and I''m short when I''m old. What am I?', 'A candle'),
('riddle', 'What is full of holes but still holds water?', 'A sponge'),
('riddle', 'What has many keys but can''t open a single lock?', 'A piano'),
('riddle', 'I have cities, but no houses. I have mountains, but no trees. I have water, but no fish. What am I?', 'A map'),
('riddle', 'What belongs to you, but everyone else uses it?', 'Your name'),
('riddle', 'What is so fragile that saying its name breaks it?', 'Silence'),
('riddle', 'What has hands but can''t clap?', 'A clock'),
('riddle', 'What has a head and a tail but no body?', 'A coin'),
('riddle', 'The more you take, the more you leave behind. What am I?', 'Footsteps'),
('riddle', 'What can travel around the world while staying in a corner?', 'A stamp'),
('riddle', 'What has one eye but can''t see?', 'A needle'),
('riddle', 'What gets wetter the more it dries?', 'A towel'),
('riddle', 'What can you catch but not throw?', 'A cold'),
('riddle', 'What has a neck but no head?', 'A bottle'),
('riddle', 'What goes up but never comes down?', 'Your age'),
('riddle', 'What can you break without touching it?', 'A promise'),
('riddle', 'What has legs but doesn''t walk?', 'A table'),
('riddle', 'What can fill a room but takes up no space?', 'Light'),
('riddle', 'What has words but never speaks?', 'A book'),
('riddle', 'What runs but never walks, has a mouth but never talks?', 'A river'),
('riddle', 'What has teeth but can''t bite?', 'A comb'),
('riddle', 'I have branches but no fruit, trunk, or leaves. What am I?', 'A bank'),
('riddle', 'What is always in front of you but can''t be seen?', 'The future'),
('riddle', 'What can you hold in your left hand but not in your right?', 'Your right elbow'),
('riddle', 'What gets bigger the more you take away?', 'A hole'),
('riddle', 'I fly without wings. I cry without eyes. What am I?', 'A cloud'),
('riddle', 'What has four wheels and flies?', 'A garbage truck'),
('riddle', 'What word is spelled incorrectly in every dictionary?', 'Incorrectly'),
('riddle', 'What building has the most stories?', 'A library');

-- JOKES (30)
INSERT INTO game_questions (category, question, answer) VALUES
('joke', 'Why don''t scientists trust atoms?', 'Because they make up everything!'),
('joke', 'What do you call a fake noodle?', 'An impasta!'),
('joke', 'Why did the scarecrow win an award?', 'Because he was outstanding in his field!'),
('joke', 'What do you call a sleeping dinosaur?', 'A dino-snore!'),
('joke', 'Why don''t eggs tell jokes?', 'They''d crack each other up!'),
('joke', 'What do you call a bear with no teeth?', 'A gummy bear!'),
('joke', 'Why did the bicycle fall over?', 'Because it was two-tired!'),
('joke', 'What do you call a fish without eyes?', 'A fsh!'),
('joke', 'Why can''t you give Elsa a balloon?', 'Because she''ll let it go!'),
('joke', 'What do you call a cow with no legs?', 'Ground beef!'),
('joke', 'Why did the math book look sad?', 'Because it had too many problems!'),
('joke', 'What do you call a lazy kangaroo?', 'A pouch potato!'),
('joke', 'Why don''t skeletons fight each other?', 'They don''t have the guts!'),
('joke', 'What do you call a dog that does magic?', 'A Labracadabrador!'),
('joke', 'Why did the cookie go to the doctor?', 'Because it was feeling crumbly!'),
('joke', 'What do you call a parade of rabbits hopping backwards?', 'A receding hare-line!'),
('joke', 'Why did the golfer bring two pairs of pants?', 'In case he got a hole in one!'),
('joke', 'What do you call a boomerang that doesn''t come back?', 'A stick!'),
('joke', 'Why did the tomato turn red?', 'Because it saw the salad dressing!'),
('joke', 'What do you call a snowman with a six-pack?', 'An abdominal snowman!'),
('joke', 'Why don''t oysters share?', 'Because they''re shellfish!'),
('joke', 'What do you call a belt made of watches?', 'A waist of time!'),
('joke', 'Why did the stadium get hot?', 'Because all the fans left!'),
('joke', 'What do you call a dinosaur that crashes their car?', 'Tyrannosaurus Wrecks!'),
('joke', 'Why did the coffee file a police report?', 'It got mugged!'),
('joke', 'What do you call a pile of cats?', 'A meow-ntain!'),
('joke', 'Why don''t calendars ever get lonely?', 'Because they have plenty of dates!'),
('joke', 'What do you call a group of unorganized cats?', 'A cat-astrophe!'),
('joke', 'Why did the invisible man turn down the job offer?', 'He couldn''t see himself doing it!'),
('joke', 'What do you call a penguin in the desert?', 'Lost!');

-- TRIVIA (30)
INSERT INTO game_questions (category, question, answer) VALUES
('trivia', 'What is the capital of Australia?', 'Canberra'),
('trivia', 'How many planets are in our solar system?', '8'),
('trivia', 'What year did the Titanic sink?', '1912'),
('trivia', 'What is the largest mammal in the world?', 'Blue whale'),
('trivia', 'Who painted the Mona Lisa?', 'Leonardo da Vinci'),
('trivia', 'What is the smallest country in the world?', 'Vatican City'),
('trivia', 'How many bones are in the adult human body?', '206'),
('trivia', 'What planet is known as the Red Planet?', 'Mars'),
('trivia', 'What is the largest ocean on Earth?', 'Pacific Ocean'),
('trivia', 'Who wrote Romeo and Juliet?', 'William Shakespeare'),
('trivia', 'What is the chemical symbol for gold?', 'Au'),
('trivia', 'In what year did World War II end?', '1945'),
('trivia', 'What is the tallest mountain in the world?', 'Mount Everest'),
('trivia', 'How many continents are there?', '7'),
('trivia', 'What is the largest planet in our solar system?', 'Jupiter'),
('trivia', 'Who was the first person to walk on the moon?', 'Neil Armstrong'),
('trivia', 'What is the capital of Japan?', 'Tokyo'),
('trivia', 'How many cards are in a standard deck?', '52'),
('trivia', 'What is the hardest natural substance on Earth?', 'Diamond'),
('trivia', 'What year did the Berlin Wall fall?', '1989'),
('trivia', 'What is the longest river in the world?', 'The Nile'),
('trivia', 'Who invented the telephone?', 'Alexander Graham Bell'),
('trivia', 'What is the speed of light in miles per second?', 'About 186,000'),
('trivia', 'What is the largest desert in the world?', 'Antarctic Desert'),
('trivia', 'How many stripes are on the American flag?', '13'),
('trivia', 'What is the currency of the United Kingdom?', 'Pound Sterling'),
('trivia', 'Who painted the Sistine Chapel ceiling?', 'Michelangelo'),
('trivia', 'What is the most spoken language in the world?', 'English (by total speakers)'),
('trivia', 'What year was the first iPhone released?', '2007'),
('trivia', 'What is the capital of Canada?', 'Ottawa');
