-- Jokes seed data
-- 50 easy, 50 medium, 50 hard jokes

-- Easy (Pre-K/Kindergarten): Simple jokes for young children
INSERT INTO jokes (question, answer, difficulty) VALUES
('What do you call a sleeping dinosaur?', 'A dino-snore!', 'easy'),
('Why did the teddy bear say no to dessert?', 'Because she was already stuffed!', 'easy'),
('What do you call a fish without eyes?', 'A fsh!', 'easy'),
('Why do cows wear bells?', 'Because their horns do not work!', 'easy'),
('What do you call a bear with no teeth?', 'A gummy bear!', 'easy'),
('Why did the banana go to the doctor?', 'Because it was not peeling well!', 'easy'),
('What do you call a dog that does magic?', 'A Labracadabrador!', 'easy'),
('Why are elephants so wrinkled?', 'Because they take too long to iron!', 'easy'),
('What do cats eat for breakfast?', 'Mice Krispies!', 'easy'),
('Why did the cookie go to the doctor?', 'Because it felt crummy!', 'easy'),
('What do you call a pig that knows karate?', 'A pork chop!', 'easy'),
('Why do birds fly south in winter?', 'Because it is too far to walk!', 'easy'),
('What time do ducks wake up?', 'At the quack of dawn!', 'easy'),
('Why did the chicken cross the playground?', 'To get to the other slide!', 'easy'),
('What do you call a cold dog?', 'A chili dog!', 'easy'),
('Why do bees have sticky hair?', 'Because they use honeycombs!', 'easy'),
('What do you call a sleeping bull?', 'A bulldozer!', 'easy'),
('Why did the cow jump over the moon?', 'Because the farmer had cold hands!', 'easy'),
('What do snowmen eat for breakfast?', 'Frosted Flakes!', 'easy'),
('Why did the sheep say moo?', 'It was learning a new language!', 'easy'),
('What do frogs like to drink?', 'Croak-a-cola!', 'easy'),
('Why are fish so smart?', 'Because they live in schools!', 'easy'),
('What do you call a train that sneezes?', 'Achoo-choo train!', 'easy'),
('Why did the orange stop?', 'Because it ran out of juice!', 'easy'),
('What is a cat''s favorite color?', 'Purr-ple!', 'easy'),
('Why do seagulls fly over the sea?', 'Because if they flew over the bay, they would be bagels!', 'easy'),
('What do you call a rabbit with fleas?', 'Bugs Bunny!', 'easy'),
('Why did the balloon go near the needle?', 'It wanted to be a pop star!', 'easy'),
('What do you call a funny mountain?', 'Hill-arious!', 'easy'),
('Why did the clock get in trouble?', 'Because it tocked too much!', 'easy'),
('What do you call a lazy kangaroo?', 'A pouch potato!', 'easy'),
('Why did the sun go to school?', 'To get brighter!', 'easy'),
('What do elves learn in school?', 'The elf-abet!', 'easy'),
('Why did the crayon cry?', 'It was feeling blue!', 'easy'),
('What is a ghost''s favorite fruit?', 'Boo-berries!', 'easy'),
('Why did the leaf go to the doctor?', 'It was feeling green!', 'easy'),
('What do you call a dancing sheep?', 'A baa-llerina!', 'easy'),
('Why did the robot go on vacation?', 'To recharge its batteries!', 'easy'),
('What is a snake''s favorite subject?', 'Hiss-tory!', 'easy'),
('Why did the tomato turn red?', 'Because it saw the salad dressing!', 'easy'),
('What do you call a cow that eats grass?', 'A lawn moo-er!', 'easy'),
('Why did the pencil go to the doctor?', 'Because it was feeling pointless!', 'easy'),
('What is an astronaut''s favorite key?', 'The space bar!', 'easy'),
('Why did the spider go on the computer?', 'To check its web site!', 'easy'),
('What do you call a happy cowboy?', 'A jolly rancher!', 'easy'),
('Why did the shoe go to the doctor?', 'It had heel problems!', 'easy'),
('What do you call a dinosaur that crashes cars?', 'Tyrannosaurus Wrecks!', 'easy'),
('Why did the music teacher go to jail?', 'Because she got in treble!', 'easy'),
('What do you get when you cross a snowman with a vampire?', 'Frostbite!', 'easy'),
('Why did the student eat homework?', 'Because the teacher said it was a piece of cake!', 'easy');

-- Medium (Elementary): Puns and wordplay jokes
INSERT INTO jokes (question, answer, difficulty) VALUES
('Why do not scientists trust atoms?', 'Because they make up everything!', 'medium'),
('What do you call a fake noodle?', 'An impasta!', 'medium'),
('Why did the scarecrow win an award?', 'Because he was outstanding in his field!', 'medium'),
('Why do not eggs tell jokes?', 'They would crack each other up!', 'medium'),
('Why did the bicycle fall over?', 'Because it was two-tired!', 'medium'),
('Why can not you give Elsa a balloon?', 'Because she will let it go!', 'medium'),
('What do you call a cow with no legs?', 'Ground beef!', 'medium'),
('Why did the math book look sad?', 'Because it had too many problems!', 'medium'),
('Why do not skeletons fight each other?', 'They do not have the guts!', 'medium'),
('What do you call a parade of rabbits hopping backwards?', 'A receding hare-line!', 'medium'),
('Why did the golfer bring two pairs of pants?', 'In case he got a hole in one!', 'medium'),
('What do you call a boomerang that does not come back?', 'A stick!', 'medium'),
('What do you call a snowman with a six-pack?', 'An abdominal snowman!', 'medium'),
('Why do not oysters share?', 'Because they are shellfish!', 'medium'),
('What do you call a belt made of watches?', 'A waist of time!', 'medium'),
('Why did the stadium get hot?', 'Because all the fans left!', 'medium'),
('Why did the coffee file a police report?', 'It got mugged!', 'medium'),
('What do you call a pile of cats?', 'A meow-ntain!', 'medium'),
('Why do not calendars ever get lonely?', 'Because they have plenty of dates!', 'medium'),
('What do you call a group of unorganized cats?', 'A cat-astrophe!', 'medium'),
('Why did the invisible man turn down the job offer?', 'He could not see himself doing it!', 'medium'),
('What do you call a penguin in the desert?', 'Lost!', 'medium'),
('Why did the computer go to the doctor?', 'Because it had a virus!', 'medium'),
('What do you call a can opener that does not work?', 'A can not opener!', 'medium'),
('Why did the tree go to the dentist?', 'To get a root canal!', 'medium'),
('What do you call a sleeping pizza?', 'A piZZZZa!', 'medium'),
('Why did the gym close down?', 'It just did not work out!', 'medium'),
('What do you call a shoe made of a banana?', 'A slipper!', 'medium'),
('Why did the scarecrow become a successful motivational speaker?', 'He was outstanding in his field!', 'medium'),
('What do you call a deer with no eyes?', 'No idea!', 'medium'),
('Why did the picture go to jail?', 'Because it was framed!', 'medium'),
('What do you call a factory that makes okay products?', 'A satisfactory!', 'medium'),
('Why did the skeleton go to the party alone?', 'He had no body to go with!', 'medium'),
('What do lawyers wear to court?', 'Lawsuits!', 'medium'),
('Why did the phone wear glasses?', 'Because it lost its contacts!', 'medium'),
('What do you call a dinosaur that takes care of its teeth?', 'A Flossiraptor!', 'medium'),
('Why did the egg hide?', 'Because it was a little chicken!', 'medium'),
('What do you call a fish wearing a bowtie?', 'Sofishticated!', 'medium'),
('Why did the lamp go to school?', 'To get a little brighter!', 'medium'),
('What do you call a bee that lives in America?', 'A USB!', 'medium'),
('Why did the banana go to the hair salon?', 'Because it had split ends!', 'medium'),
('What do you call a cow in an earthquake?', 'A milkshake!', 'medium'),
('Why did the nose feel sad?', 'Because it was always getting picked on!', 'medium'),
('What do you call a bear in the rain?', 'A drizzly bear!', 'medium'),
('Why did the music note go to jail?', 'Because it got in trouble with the staff!', 'medium'),
('What do you call a dog magician?', 'A Labracadabrador!', 'medium'),
('Why did the broom get a promotion?', 'Because it swept the competition!', 'medium'),
('What do you call a dinosaur ghost?', 'A scaredactyl!', 'medium'),
('Why did the duck put lipstick on?', 'Because it was getting ready for a hot date!', 'medium'),
('What do you call an alligator wearing a vest?', 'An investigator!', 'medium');

-- Hard (Middle School+): More sophisticated humor and complex puns
INSERT INTO jokes (question, answer, difficulty) VALUES
('Why do programmers prefer dark mode?', 'Because light attracts bugs!', 'hard'),
('What do you call a number that cannot keep still?', 'A roamin numeral!', 'hard'),
('Why did the physics teacher break up with the biology teacher?', 'There was no chemistry!', 'hard'),
('What did the DNA say to the other DNA?', 'Do these genes make me look fat?', 'hard'),
('Why do chemists like nitrates so much?', 'They are cheaper than day rates!', 'hard'),
('What is the difference between a cat and a comma?', 'One has claws at the end of its paws, the other is a pause at the end of a clause!', 'hard'),
('Why did the obtuse angle go to the beach?', 'Because it was over 90 degrees!', 'hard'),
('What did the ocean say to the beach?', 'Nothing, it just waved!', 'hard'),
('Why are chemists excellent for solving problems?', 'They have all the solutions!', 'hard'),
('What do you call eight hobbits?', 'A hobbyte!', 'hard'),
('Why did Schrödinger''s cat cross the road?', 'It did and it did not!', 'hard'),
('What did the photon say when asked if it wanted to check luggage?', 'No thanks, I am traveling light!', 'hard'),
('Why is the math book always unhappy?', 'It has too many problems it cannot solve!', 'hard'),
('What did the grape say when it got stepped on?', 'Nothing, it just let out a little wine!', 'hard'),
('Why do programmers hate nature?', 'It has too many bugs!', 'hard'),
('What is a physicist''s favorite food?', 'Fission chips!', 'hard'),
('Why was the math lecture so long?', 'The professor kept going off on a tangent!', 'hard'),
('What did one ion say to the other?', 'I have got my ion you!', 'hard'),
('Why did the scarecrow become a neurosurgeon?', 'Because he was already outstanding in his field!', 'hard'),
('What is the fastest way to determine the sex of a chromosome?', 'Pull down its genes!', 'hard'),
('Why do ambassadors never get sick?', 'Diplomatic immunity!', 'hard'),
('What do you call a singing laptop?', 'A Dell!', 'hard'),
('Why did Pavlov have such soft hair?', 'He conditioned it!', 'hard'),
('What is the difference between ignorance and apathy?', 'I do not know and I do not care!', 'hard'),
('Why did the hipster burn his tongue?', 'He drank his coffee before it was cool!', 'hard'),
('What do you get when you put root beer in a square glass?', 'Beer!', 'hard'),
('Why do Java developers wear glasses?', 'Because they do not C#!', 'hard'),
('What did the biologist wear to impress their date?', 'Designer genes!', 'hard'),
('Why should you never trust atoms?', 'Because they literally make up everything!', 'hard'),
('What did the proton say to the electron?', 'Stop being so negative!', 'hard'),
('Why did the statistician drown crossing the river?', 'It was three feet deep on average!', 'hard'),
('What is a computer''s least favorite food?', 'Spam!', 'hard'),
('Why did Beethoven get rid of his chickens?', 'All they said was Bach, Bach, Bach!', 'hard'),
('What do you call a mathematician who spent all summer at the beach?', 'A tan gent!', 'hard'),
('Why is the obtuse triangle always so frustrated?', 'Because it is never right!', 'hard'),
('What did the zero say to the eight?', 'Nice belt!', 'hard'),
('Why do not programmers like nature?', 'It has too many bugs and no debugging tool!', 'hard'),
('What is Forrest Gump''s email password?', '1forrest1!', 'hard'),
('Why did the electron leave the atom?', 'Because it felt negative!', 'hard'),
('What does a subatomic duck say?', 'Quark quark!', 'hard'),
('Why was the calculus teacher bad at baseball?', 'He was better at integration than differentiation!', 'hard'),
('What do you call a dinosaur that knows a lot of words?', 'A thesaurus!', 'hard'),
('Why did the database administrator leave his wife?', 'She had one-to-many relationships!', 'hard'),
('What did the mitochondria say to the cell?', 'I am the powerhouse!', 'hard'),
('Why do geologists make bad comedians?', 'They take everything for granite!', 'hard'),
('What is the integral of 1 over cabin?', 'A natural log cabin plus sea!', 'hard'),
('Why did the noble gas cry?', 'Because all his friends argon!', 'hard'),
('What do you get when you combine sulfur, tungsten, and silver?', 'SWAg!', 'hard'),
('Why was the thermometer smarter than the graduated cylinder?', 'It had more degrees!', 'hard'),
('Why did the developer go broke?', 'Because he used up all his cache!', 'hard');
