-- Riddles seed data
-- 50 easy, 50 medium, 50 hard riddles

-- Easy (Pre-K/Kindergarten): Simple riddles with obvious answers
INSERT INTO riddles (question, answer, difficulty) VALUES
('I am yellow and monkeys love to eat me. What am I?', 'A banana', 'easy'),
('I have four legs but cannot walk. What am I?', 'A table', 'easy'),
('I am round and you kick me. What am I?', 'A ball', 'easy'),
('I shine in the sky during the day. What am I?', 'The sun', 'easy'),
('I am cold and white and fall from the sky. What am I?', 'Snow', 'easy'),
('I have hands but cannot clap. What am I?', 'A clock', 'easy'),
('I am orange and rabbits love me. What am I?', 'A carrot', 'easy'),
('I have wheels and go beep beep. What am I?', 'A car', 'easy'),
('I bark and wag my tail. What am I?', 'A dog', 'easy'),
('I am green and hop. What am I?', 'A frog', 'easy'),
('I have wings and say tweet tweet. What am I?', 'A bird', 'easy'),
('I am round and you eat me for breakfast. What am I?', 'An egg', 'easy'),
('I have a trunk but I am not a car. What am I?', 'An elephant', 'easy'),
('I am red and grow on trees. What am I?', 'An apple', 'easy'),
('I meow and drink milk. What am I?', 'A cat', 'easy'),
('I have petals and grow in gardens. What am I?', 'A flower', 'easy'),
('I am yellow and bees make me. What am I?', 'Honey', 'easy'),
('I fall from clouds but I am not snow. What am I?', 'Rain', 'easy'),
('I have pages and you read me. What am I?', 'A book', 'easy'),
('I swim in the ocean and have fins. What am I?', 'A fish', 'easy'),
('I am white and you drink me. Cows make me. What am I?', 'Milk', 'easy'),
('I have a shell and move slowly. What am I?', 'A turtle', 'easy'),
('I am cold and you put me in drinks. What am I?', 'Ice', 'easy'),
('I shine at night in the sky. What am I?', 'The moon', 'easy'),
('I am fluffy and float in the sky. What am I?', 'A cloud', 'easy'),
('I have stripes and say buzz. What am I?', 'A bee', 'easy'),
('I am tall and have branches and leaves. What am I?', 'A tree', 'easy'),
('I am small and say squeak. What am I?', 'A mouse', 'easy'),
('You wear me on your head. What am I?', 'A hat', 'easy'),
('I have numbers and you tell time with me. What am I?', 'A clock', 'easy'),
('I am brown and dogs love me. What am I?', 'A bone', 'easy'),
('I come in many colors and you draw with me. What am I?', 'Crayons', 'easy'),
('I am sweet and you eat me on your birthday. What am I?', 'Cake', 'easy'),
('I have strings and make music. What am I?', 'A guitar', 'easy'),
('I bounce and you play basketball with me. What am I?', 'A basketball', 'easy'),
('I am long and yellow and you write with me. What am I?', 'A pencil', 'easy'),
('I have a blade and cut paper. What am I?', 'Scissors', 'easy'),
('I am wet and you swim in me. What am I?', 'A pool', 'easy'),
('I am striped and black and white. What am I?', 'A zebra', 'easy'),
('I spin and have eight legs. What am I?', 'A spider', 'easy'),
('I am pink and oink. What am I?', 'A pig', 'easy'),
('I am soft and you sleep on me. What am I?', 'A pillow', 'easy'),
('I have keys but open no doors. What am I?', 'A piano', 'easy'),
('I am tall and you climb me. What am I?', 'A ladder', 'easy'),
('You wear me on your feet. What am I?', 'Shoes', 'easy'),
('I am red and trucks use me to put out fires. What am I?', 'Water', 'easy'),
('I have a tail and chase mice. What am I?', 'A cat', 'easy'),
('I am square and you watch me. What am I?', 'A TV', 'easy'),
('I am colorful and fly. What am I?', 'A butterfly', 'easy'),
('I ring and you answer me. What am I?', 'A phone', 'easy');

-- Medium (Elementary): Classic riddles with wordplay
INSERT INTO riddles (question, answer, difficulty) VALUES
('What has to be broken before you can use it?', 'An egg', 'medium'),
('I am tall when I am young, and short when I am old. What am I?', 'A candle', 'medium'),
('What is full of holes but still holds water?', 'A sponge', 'medium'),
('What has many keys but cannot open a single lock?', 'A piano', 'medium'),
('What belongs to you, but everyone else uses it?', 'Your name', 'medium'),
('What gets wetter the more it dries?', 'A towel', 'medium'),
('What can you catch but not throw?', 'A cold', 'medium'),
('What has a head and a tail but no body?', 'A coin', 'medium'),
('What goes up but never comes down?', 'Your age', 'medium'),
('What can you break without touching it?', 'A promise', 'medium'),
('What has a neck but no head?', 'A bottle', 'medium'),
('What can fill a room but takes up no space?', 'Light', 'medium'),
('What has words but never speaks?', 'A book', 'medium'),
('What has one eye but cannot see?', 'A needle', 'medium'),
('What runs but never walks?', 'Water', 'medium'),
('What has teeth but cannot bite?', 'A comb', 'medium'),
('What gets bigger the more you take away?', 'A hole', 'medium'),
('What can travel around the world while staying in a corner?', 'A stamp', 'medium'),
('What has legs but does not walk?', 'A table', 'medium'),
('What kind of room has no doors or windows?', 'A mushroom', 'medium'),
('What goes through towns and over hills but never moves?', 'A road', 'medium'),
('What has ears but cannot hear?', 'Corn', 'medium'),
('What has a thumb and four fingers but is not alive?', 'A glove', 'medium'),
('What comes once in a minute, twice in a moment, but never in a thousand years?', 'The letter M', 'medium'),
('What building has the most stories?', 'A library', 'medium'),
('What invention lets you look through a wall?', 'A window', 'medium'),
('What has a face and two hands but no arms or legs?', 'A clock', 'medium'),
('What can you hold in your left hand but not your right?', 'Your right elbow', 'medium'),
('What is always in front of you but cannot be seen?', 'The future', 'medium'),
('What word is spelled incorrectly in every dictionary?', 'Incorrectly', 'medium'),
('What has four wheels and flies?', 'A garbage truck', 'medium'),
('What is so fragile that saying its name breaks it?', 'Silence', 'medium'),
('What runs around a yard without moving?', 'A fence', 'medium'),
('What can be cracked, made, told, and played?', 'A joke', 'medium'),
('What has a bottom at the top?', 'Your legs', 'medium'),
('What is cut on a table but never eaten?', 'A deck of cards', 'medium'),
('What word becomes shorter when you add two letters?', 'Short', 'medium'),
('What tastes better than it smells?', 'A tongue', 'medium'),
('What can run but never walks, has a mouth but never talks?', 'A river', 'medium'),
('What do you throw out when you want to use it, and take in when you do not?', 'An anchor', 'medium'),
('What has cities but no houses, forests but no trees?', 'A map', 'medium'),
('What starts with T, ends with T, and has T in it?', 'A teapot', 'medium'),
('What is black when you buy it, red when you use it, and gray when you throw it away?', 'Charcoal', 'medium'),
('What has 13 hearts but no other organs?', 'A deck of cards', 'medium'),
('What flies without wings?', 'Time', 'medium'),
('What grows when it eats but dies when it drinks?', 'Fire', 'medium'),
('What goes up and down but does not move?', 'Stairs', 'medium'),
('What can you keep after giving it to someone?', 'Your word', 'medium'),
('What bank has no money?', 'A river bank', 'medium'),
('What coat is always wet when you put it on?', 'A coat of paint', 'medium');

-- Hard (Middle School+): Complex riddles requiring abstract thinking
INSERT INTO riddles (question, answer, difficulty) VALUES
('I have cities, but no houses. I have mountains, but no trees. I have water, but no fish. What am I?', 'A map', 'hard'),
('The more you take, the more you leave behind. What am I?', 'Footsteps', 'hard'),
('I speak without a mouth and hear without ears. I have no body, but I come alive with the wind. What am I?', 'An echo', 'hard'),
('I can be cracked, made, told, and played. What am I?', 'A joke', 'hard'),
('I have branches but no fruit, trunk, or leaves. What am I?', 'A bank', 'hard'),
('I fly without wings. I cry without eyes. Wherever I go, darkness follows me. What am I?', 'A cloud', 'hard'),
('The person who makes it, sells it. The person who buys it never uses it. The person who uses it never knows they are using it. What is it?', 'A coffin', 'hard'),
('I am not alive, but I grow. I do not have lungs, but I need air. I do not have a mouth, but water kills me. What am I?', 'Fire', 'hard'),
('What disappears as soon as you say its name?', 'Silence', 'hard'),
('I have keys but no locks. I have space but no room. You can enter but cannot go inside. What am I?', 'A keyboard', 'hard'),
('What can fill a room but takes up no space?', 'Light', 'hard'),
('I am always hungry and will die if not fed, but whatever I touch will soon turn red. What am I?', 'Fire', 'hard'),
('What English word has three consecutive double letters?', 'Bookkeeper', 'hard'),
('I am taken from a mine and shut in a wooden case. I am never released, yet I am used by almost everyone. What am I?', 'Pencil lead', 'hard'),
('What five-letter word becomes shorter when you add two letters?', 'Short', 'hard'),
('I am seen in the water and seen in the sky. I am in the rainbow and a jay''s feather. What am I?', 'Blue', 'hard'),
('What can bring back the dead, make you cry, make you laugh, and make you young?', 'Memories', 'hard'),
('What is it that given one, you will have either two or none?', 'A choice', 'hard'),
('I am a word of letters three. Add two and fewer there will be. What am I?', 'Few', 'hard'),
('What word in the English language does the following: the first two letters signify a male, the first three letters signify a female, the first four letters signify a great, while the entire word signifies a great woman?', 'Heroine', 'hard'),
('I am the beginning of the end, and the end of time and space. I am essential to creation, and I surround every place. What am I?', 'The letter E', 'hard'),
('What is seen in the middle of March and April that cannot be seen at the beginning or end of either month?', 'The letter R', 'hard'),
('Forward I am heavy, but backward I am not. What am I?', 'Ton', 'hard'),
('What has a head, a tail, is brown, and has no legs?', 'A penny', 'hard'),
('What gets broken without being held?', 'A promise', 'hard'),
('I make two people out of one. What am I?', 'A mirror', 'hard'),
('I can only live where there is light, but I die if the light shines on me. What am I?', 'A shadow', 'hard'),
('The one who makes me does not need me. The one who buys me does not use me. The one who uses me does not know they are using me. What am I?', 'A coffin', 'hard'),
('What begins with an E but only contains one letter?', 'An envelope', 'hard'),
('I am lighter than air but a million men cannot lift me. What am I?', 'A bubble', 'hard'),
('What appears once in a minute, twice in a moment, but not once in a thousand years?', 'The letter M', 'hard'),
('Poor people have it. Rich people need it. If you eat it you die. What is it?', 'Nothing', 'hard'),
('What belongs to you but is used more by others?', 'Your name', 'hard'),
('I am an odd number. Take away one letter and I become even. What number am I?', 'Seven', 'hard'),
('What 8-letter word can have a letter taken away and still make a word, repeatedly until you have one letter left?', 'Starting', 'hard'),
('A man is looking at a photograph of someone. His friend asks who it is. The man replies: Brothers and sisters, I have none. But that man''s father is my father''s son. Who is in the photograph?', 'His son', 'hard'),
('What is greater than God, more evil than the devil, the poor have it, the rich need it, and if you eat it, you will die?', 'Nothing', 'hard'),
('I have lakes with no water, mountains with no stone, and cities with no buildings. What am I?', 'A map', 'hard'),
('Two fathers and two sons go fishing. They each catch one fish. They bring home only three fish. Why?', 'They are grandfather, father, and son', 'hard'),
('What gets whiter the dirtier it gets?', 'A chalkboard', 'hard'),
('I am always on the dinner table, but you do not eat me. What am I?', 'Plates and silverware', 'hard'),
('What has a spine but no bones?', 'A book', 'hard'),
('What runs all around a backyard, yet never moves?', 'A fence', 'hard'),
('What room do ghosts avoid?', 'The living room', 'hard'),
('What has many needles but does not sew?', 'A Christmas tree', 'hard'),
('What can you catch but never throw?', 'A cold', 'hard'),
('I have no life, but I can die. What am I?', 'A battery', 'hard'),
('What type of dress can never be worn?', 'An address', 'hard'),
('What kind of tree can you carry in your hand?', 'A palm', 'hard'),
('What word looks the same upside down and backwards?', 'SWIMS', 'hard');
