-- Trivia questions seed data
-- 50 easy, 50 medium, 50 hard questions

-- Easy (Pre-K/Kindergarten): Simple facts about colors, animals, shapes, counting
INSERT INTO trivia_questions (question, answer, difficulty) VALUES
('What color is the sky on a sunny day?', 'Blue', 'easy'),
('How many legs does a dog have?', '4', 'easy'),
('What animal says "moo"?', 'A cow', 'easy'),
('What shape is a ball?', 'Circle', 'easy'),
('What color is grass?', 'Green', 'easy'),
('How many eyes do you have?', '2', 'easy'),
('What animal says "meow"?', 'A cat', 'easy'),
('What do you use to write?', 'A pencil', 'easy'),
('What is frozen water called?', 'Ice', 'easy'),
('What color is a banana?', 'Yellow', 'easy'),
('How many fingers do you have on one hand?', '5', 'easy'),
('What animal has a long trunk?', 'An elephant', 'easy'),
('What do bees make?', 'Honey', 'easy'),
('What color is an apple?', 'Red', 'easy'),
('What shape has three sides?', 'Triangle', 'easy'),
('What do you sleep in at night?', 'A bed', 'easy'),
('What animal hops and has long ears?', 'A rabbit', 'easy'),
('What color is snow?', 'White', 'easy'),
('How many wheels does a bicycle have?', '2', 'easy'),
('What do fish live in?', 'Water', 'easy'),
('What gives us light during the day?', 'The sun', 'easy'),
('What animal says "oink"?', 'A pig', 'easy'),
('What shape is a door?', 'Rectangle', 'easy'),
('What do birds have that help them fly?', 'Wings', 'easy'),
('What color is the sun?', 'Yellow', 'easy'),
('How many days are in a week?', '7', 'easy'),
('What animal has a shell on its back?', 'A turtle', 'easy'),
('What do you wear on your feet?', 'Shoes', 'easy'),
('What comes after the number 5?', '6', 'easy'),
('What animal says "quack"?', 'A duck', 'easy'),
('What do you use to eat soup?', 'A spoon', 'easy'),
('What color is an orange?', 'Orange', 'easy'),
('What shape is a pizza?', 'Circle', 'easy'),
('What do cows give us to drink?', 'Milk', 'easy'),
('How many ears do you have?', '2', 'easy'),
('What animal has black and white stripes?', 'A zebra', 'easy'),
('What falls from clouds when it rains?', 'Water', 'easy'),
('What shape has four equal sides?', 'Square', 'easy'),
('What do we call baby dogs?', 'Puppies', 'easy'),
('What color is chocolate?', 'Brown', 'easy'),
('What do you brush every day?', 'Your teeth', 'easy'),
('What animal lives in a hive?', 'Bees', 'easy'),
('How many months are in a year?', '12', 'easy'),
('What do chickens lay?', 'Eggs', 'easy'),
('What color is a fire truck?', 'Red', 'easy'),
('What animal says "baa"?', 'A sheep', 'easy'),
('What do you drink when you are thirsty?', 'Water', 'easy'),
('What is the opposite of hot?', 'Cold', 'easy'),
('What do we call baby cats?', 'Kittens', 'easy'),
('What shines in the sky at night?', 'Stars', 'easy');

-- Medium (Elementary): General knowledge for ages 6-12
INSERT INTO trivia_questions (question, answer, difficulty) VALUES
('What is the capital of the United States?', 'Washington D.C.', 'medium'),
('How many continents are there?', '7', 'medium'),
('What planet do we live on?', 'Earth', 'medium'),
('How many colors are in a rainbow?', '7', 'medium'),
('What is the largest animal in the ocean?', 'Blue whale', 'medium'),
('What gas do plants breathe in?', 'Carbon dioxide', 'medium'),
('How many sides does a hexagon have?', '6', 'medium'),
('What is the fastest land animal?', 'Cheetah', 'medium'),
('Which planet is known as the Red Planet?', 'Mars', 'medium'),
('What do caterpillars turn into?', 'Butterflies', 'medium'),
('How many planets are in our solar system?', '8', 'medium'),
('What is the largest continent?', 'Asia', 'medium'),
('What instrument has 88 keys?', 'Piano', 'medium'),
('What is the capital of France?', 'Paris', 'medium'),
('How many bones do adults have?', '206', 'medium'),
('What is the tallest animal?', 'Giraffe', 'medium'),
('Which ocean is the largest?', 'Pacific Ocean', 'medium'),
('What country is famous for pizza?', 'Italy', 'medium'),
('How many states are in the United States?', '50', 'medium'),
('What is the hardest natural substance?', 'Diamond', 'medium'),
('What is baby sheep called?', 'A lamb', 'medium'),
('Which planet has rings around it?', 'Saturn', 'medium'),
('What is the capital of England?', 'London', 'medium'),
('How many teeth do adult humans have?', '32', 'medium'),
('What is the largest bird in the world?', 'Ostrich', 'medium'),
('What country is the Great Wall located in?', 'China', 'medium'),
('What is the closest star to Earth?', 'The Sun', 'medium'),
('How many legs does a spider have?', '8', 'medium'),
('What is the capital of Japan?', 'Tokyo', 'medium'),
('What metal is attracted to magnets?', 'Iron', 'medium'),
('What is the largest desert in the world?', 'Antarctic Desert', 'medium'),
('How many zeros are in one million?', '6', 'medium'),
('What is the smallest planet in our solar system?', 'Mercury', 'medium'),
('What country gave the Statue of Liberty to the US?', 'France', 'medium'),
('What gas do humans breathe out?', 'Carbon dioxide', 'medium'),
('How many hearts does an octopus have?', '3', 'medium'),
('What is the capital of Australia?', 'Canberra', 'medium'),
('What is the longest river in the world?', 'The Nile', 'medium'),
('What country is known for kangaroos?', 'Australia', 'medium'),
('How many minutes are in one hour?', '60', 'medium'),
('What is the largest planet in our solar system?', 'Jupiter', 'medium'),
('What is the capital of Canada?', 'Ottawa', 'medium'),
('What animal is known as the King of the Jungle?', 'Lion', 'medium'),
('How many hours are in one day?', '24', 'medium'),
('What is the smallest ocean?', 'Arctic Ocean', 'medium'),
('What language is spoken in Brazil?', 'Portuguese', 'medium'),
('How many wings does a butterfly have?', '4', 'medium'),
('What is the capital of Germany?', 'Berlin', 'medium'),
('What mountain is the tallest in the world?', 'Mount Everest', 'medium'),
('What year did the Titanic sink?', '1912', 'medium');

-- Hard (Middle School+): Challenging trivia for teens and adults
INSERT INTO trivia_questions (question, answer, difficulty) VALUES
('Who painted the Mona Lisa?', 'Leonardo da Vinci', 'hard'),
('What is the chemical symbol for gold?', 'Au', 'hard'),
('In what year did World War II end?', '1945', 'hard'),
('Who was the first person to walk on the moon?', 'Neil Armstrong', 'hard'),
('What is the capital of Mongolia?', 'Ulaanbaatar', 'hard'),
('How many chromosomes do humans have?', '46', 'hard'),
('Who wrote Romeo and Juliet?', 'William Shakespeare', 'hard'),
('What is the speed of light in miles per second?', 'About 186,000', 'hard'),
('What year did the Berlin Wall fall?', '1989', 'hard'),
('Who invented the telephone?', 'Alexander Graham Bell', 'hard'),
('What is the smallest country in the world?', 'Vatican City', 'hard'),
('What is the chemical formula for water?', 'H2O', 'hard'),
('Who painted the Sistine Chapel ceiling?', 'Michelangelo', 'hard'),
('What year was the first iPhone released?', '2007', 'hard'),
('What is the currency of Japan?', 'Yen', 'hard'),
('How many stripes are on the American flag?', '13', 'hard'),
('What is the capital of Egypt?', 'Cairo', 'hard'),
('Who discovered penicillin?', 'Alexander Fleming', 'hard'),
('What is the largest organ in the human body?', 'Skin', 'hard'),
('What element has the atomic number 1?', 'Hydrogen', 'hard'),
('Who wrote the Harry Potter series?', 'J.K. Rowling', 'hard'),
('What is the capital of South Korea?', 'Seoul', 'hard'),
('How many symphonies did Beethoven compose?', '9', 'hard'),
('What is the longest bone in the human body?', 'Femur', 'hard'),
('What year did the French Revolution begin?', '1789', 'hard'),
('Who developed the theory of relativity?', 'Albert Einstein', 'hard'),
('What is the capital of Thailand?', 'Bangkok', 'hard'),
('How many cards are in a standard deck?', '52', 'hard'),
('What is the currency of the United Kingdom?', 'Pound Sterling', 'hard'),
('Who painted The Starry Night?', 'Vincent van Gogh', 'hard'),
('What is the chemical symbol for iron?', 'Fe', 'hard'),
('What year did the American Civil War end?', '1865', 'hard'),
('What is the capital of Argentina?', 'Buenos Aires', 'hard'),
('Who invented the light bulb?', 'Thomas Edison', 'hard'),
('What is the deepest ocean trench?', 'Mariana Trench', 'hard'),
('What language has the most native speakers?', 'Mandarin Chinese', 'hard'),
('What is the capital of Turkey?', 'Ankara', 'hard'),
('Who wrote 1984?', 'George Orwell', 'hard'),
('What is the chemical symbol for sodium?', 'Na', 'hard'),
('What year did man first land on the moon?', '1969', 'hard'),
('What is the largest lake in Africa?', 'Lake Victoria', 'hard'),
('Who composed the Four Seasons?', 'Vivaldi', 'hard'),
('What is the capital of Vietnam?', 'Hanoi', 'hard'),
('How many elements are in the periodic table?', '118', 'hard'),
('What is the longest river in the United States?', 'Missouri River', 'hard'),
('Who discovered gravity?', 'Isaac Newton', 'hard'),
('What is the capital of Morocco?', 'Rabat', 'hard'),
('What year was the Declaration of Independence signed?', '1776', 'hard'),
('What is the chemical symbol for silver?', 'Ag', 'hard'),
('Who painted The Last Supper?', 'Leonardo da Vinci', 'hard');
