-- True/False questions seed data
-- 50 easy, 50 medium, 50 hard questions

-- Easy (Pre-K/Kindergarten): Simple facts for young children
INSERT INTO true_false_questions (statement, answer, difficulty) VALUES
('The sun is hot.', true, 'easy'),
('Dogs can fly.', false, 'easy'),
('Bananas are yellow.', true, 'easy'),
('Fish live in water.', true, 'easy'),
('The moon is made of cheese.', false, 'easy'),
('Cats say meow.', true, 'easy'),
('Ice is cold.', true, 'easy'),
('Birds have four legs.', false, 'easy'),
('Apples grow on trees.', true, 'easy'),
('Elephants are small animals.', false, 'easy'),
('Snow is white.', true, 'easy'),
('Pigs can oink.', true, 'easy'),
('The sky is green.', false, 'easy'),
('Cows give us milk.', true, 'easy'),
('Frogs can hop.', true, 'easy'),
('Rabbits have long ears.', true, 'easy'),
('Fire is cold.', false, 'easy'),
('Grass is usually green.', true, 'easy'),
('Bees make honey.', true, 'easy'),
('Fish can walk on land.', false, 'easy'),
('The alphabet has 26 letters.', true, 'easy'),
('Horses can run fast.', true, 'easy'),
('Rocks are soft.', false, 'easy'),
('Rain comes from clouds.', true, 'easy'),
('Spiders have six legs.', false, 'easy'),
('Oranges are orange.', true, 'easy'),
('Chickens lay eggs.', true, 'easy'),
('Trees can walk.', false, 'easy'),
('Water is wet.', true, 'easy'),
('Snakes have legs.', false, 'easy'),
('The Earth is round.', true, 'easy'),
('Ducks say quack.', true, 'easy'),
('Carrots are blue.', false, 'easy'),
('Butterflies can fly.', true, 'easy'),
('Babies drink milk.', true, 'easy'),
('Stars shine at night.', true, 'easy'),
('Turtles are fast.', false, 'easy'),
('Lemons are sweet.', false, 'easy'),
('Bears are animals.', true, 'easy'),
('Flowers need water to grow.', true, 'easy'),
('The sun comes out at night.', false, 'easy'),
('Whales live in the ocean.', true, 'easy'),
('Shoes go on your hands.', false, 'easy'),
('Monkeys like bananas.', true, 'easy'),
('Penguins can fly.', false, 'easy'),
('You sleep in a bed.', true, 'easy'),
('Giraffes have long necks.', true, 'easy'),
('Balls are square.', false, 'easy'),
('You eat food with your ears.', false, 'easy'),
('Dogs are pets.', true, 'easy');

-- Medium (Elementary): General knowledge for ages 6-12
INSERT INTO true_false_questions (statement, answer, difficulty) VALUES
('There are seven continents on Earth.', true, 'medium'),
('The Great Wall of China can be seen from space with the naked eye.', false, 'medium'),
('Dolphins are fish.', false, 'medium'),
('Mount Everest is the tallest mountain in the world.', true, 'medium'),
('Humans have five senses.', true, 'medium'),
('The Pacific Ocean is the largest ocean.', true, 'medium'),
('Lightning never strikes the same place twice.', false, 'medium'),
('Bats are blind.', false, 'medium'),
('There are 50 states in the United States.', true, 'medium'),
('Goldfish have a three-second memory.', false, 'medium'),
('The human body has 206 bones.', true, 'medium'),
('Chameleons change color to match their surroundings.', false, 'medium'),
('Venus is the hottest planet in our solar system.', true, 'medium'),
('Sharks are mammals.', false, 'medium'),
('A group of lions is called a pride.', true, 'medium'),
('Octopuses have three hearts.', true, 'medium'),
('The Sahara is the largest desert in the world.', false, 'medium'),
('Sound travels faster than light.', false, 'medium'),
('Diamonds are made of carbon.', true, 'medium'),
('Spiders are insects.', false, 'medium'),
('The Amazon River is in South America.', true, 'medium'),
('Camels store water in their humps.', false, 'medium'),
('A year on Mars is longer than a year on Earth.', true, 'medium'),
('All planets in our solar system have moons.', false, 'medium'),
('Tomatoes are fruits.', true, 'medium'),
('Ostriches bury their heads in the sand.', false, 'medium'),
('The heart is located on the left side of the body.', false, 'medium'),
('Honey never spoils.', true, 'medium'),
('Koalas are bears.', false, 'medium'),
('The Nile is the longest river in the world.', true, 'medium'),
('Humans and dinosaurs lived at the same time.', false, 'medium'),
('An octopus has blue blood.', true, 'medium'),
('Mount Rushmore is in South Dakota.', true, 'medium'),
('The tongue is the strongest muscle in the body.', false, 'medium'),
('Bamboo is a type of grass.', true, 'medium'),
('Crocodiles can stick out their tongues.', false, 'medium'),
('The Great Pyramid of Giza is in Egypt.', true, 'medium'),
('Penguins live in the Arctic.', false, 'medium'),
('A strawberry is not actually a berry.', true, 'medium'),
('Humans can see all colors of light.', false, 'medium'),
('Jupiter is the largest planet in our solar system.', true, 'medium'),
('Sloths sleep about 20 hours a day.', false, 'medium'),
('The Statue of Liberty was a gift from France.', true, 'medium'),
('Bananas grow on trees.', false, 'medium'),
('An eagle can see a rabbit from two miles away.', true, 'medium'),
('Polar bears have white fur.', false, 'medium'),
('Australia is both a country and a continent.', true, 'medium'),
('Goldfish can live for over 40 years.', true, 'medium'),
('All birds can fly.', false, 'medium'),
('Horses sleep standing up.', true, 'medium');

-- Hard (Middle School+): Challenging facts for teens and adults
INSERT INTO true_false_questions (statement, answer, difficulty) VALUES
('Napoleon Bonaparte was short for his time.', false, 'hard'),
('Cleopatra lived closer in time to the Moon landing than to the building of the Great Pyramid.', true, 'hard'),
('Humans share about 60% of their DNA with bananas.', true, 'hard'),
('The inventor of the Pringles can is buried in one.', true, 'hard'),
('Oxford University is older than the Aztec Empire.', true, 'hard'),
('Vikings wore horned helmets.', false, 'hard'),
('A day on Venus is longer than a year on Venus.', true, 'hard'),
('Einstein failed math in school.', false, 'hard'),
('Goldfish have a memory span of only a few seconds.', false, 'hard'),
('The Eiffel Tower can grow taller in summer.', true, 'hard'),
('There are more trees on Earth than stars in the Milky Way.', true, 'hard'),
('The Great Fire of London killed thousands of people.', false, 'hard'),
('Hot water freezes faster than cold water.', true, 'hard'),
('George Washington had wooden teeth.', false, 'hard'),
('Russia has 11 time zones.', true, 'hard'),
('The human brain uses 10% of its capacity.', false, 'hard'),
('Wombat droppings are cube-shaped.', true, 'hard'),
('The Mona Lisa has no eyebrows.', true, 'hard'),
('Bulls are angered by the color red.', false, 'hard'),
('Humans can only survive a few days without water.', true, 'hard'),
('Mount Everest grows about 4 millimeters every year.', true, 'hard'),
('Fortune cookies were invented in China.', false, 'hard'),
('A jiffy is an actual unit of time.', true, 'hard'),
('The Great Wall of China is visible from the Moon.', false, 'hard'),
('Coca-Cola was originally green.', false, 'hard'),
('Scotland''s national animal is the unicorn.', true, 'hard'),
('Fingernails and toenails grow at the same rate.', false, 'hard'),
('Honey is the only food that never spoils.', true, 'hard'),
('Walt Disney was cryogenically frozen.', false, 'hard'),
('Sharks existed before trees.', true, 'hard'),
('Water can boil and freeze at the same time.', true, 'hard'),
('The inventor of the light bulb was afraid of the dark.', false, 'hard'),
('Octopuses have nine brains.', true, 'hard'),
('Marie Curie''s notebooks are still radioactive.', true, 'hard'),
('The shortest war in history lasted 38 minutes.', true, 'hard'),
('Humans are the only animals that blush.', true, 'hard'),
('A group of flamingos is called a flamboyance.', true, 'hard'),
('The inventor of the Frisbee was turned into a Frisbee.', true, 'hard'),
('The average person swallows eight spiders per year while sleeping.', false, 'hard'),
('Saturn could float in water if there was a bathtub big enough.', true, 'hard'),
('Cleopatra was Egyptian.', false, 'hard'),
('Bananas are radioactive.', true, 'hard'),
('The first computer programmer was a woman.', true, 'hard'),
('Rubber bands last longer when refrigerated.', true, 'hard'),
('The dot over the letter i is called a tittle.', true, 'hard'),
('Humans glow in the dark.', true, 'hard'),
('A cockroach can live for weeks without its head.', true, 'hard'),
('The Bible is the most shoplifted book in the world.', true, 'hard'),
('The total weight of all ants on Earth exceeds the weight of all humans.', true, 'hard'),
('Your taste buds are replaced every two weeks.', true, 'hard');
