/// A custom face generated by the user
class CustomFace {
  final String id;
  final String description;
  final String localPath;
  final DateTime createdAt;

  const CustomFace({
    required this.id,
    required this.description,
    required this.localPath,
    required this.createdAt,
  });

  factory CustomFace.fromJson(Map<String, dynamic> json) {
    return CustomFace(
      id: json['id'] as String,
      description: json['description'] as String,
      localPath: json['localPath'] as String,
      createdAt: DateTime.parse(json['createdAt'] as String),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'description': description,
      'localPath': localPath,
      'createdAt': createdAt.toIso8601String(),
    };
  }
}
